name: Spacegame.Web-GCR
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}    
        
    - name: Build and Tag image
      run: |
        docker build -f $GITHUB_WORKSPACE/Dockerfile -t tailspinspacegameweb:${{ github.run_number }} .
        docker tag tailspinspacegameweb:${{ github.run_number }} ghcr.io/lifeonland/tailspinspacegameweb:${{ github.run_number }}
   
    - name: Push image
      run: |
        docker push ghcr.io/lifeonland/tailspinspacegameweb:${{ github.run_number }}
    
